name: PR CI

on:
    pull_request:
        branches: [main]
        paths:
            - backend/**
            - data-engineering/**
            - .github/workflows/**

concurrency:
    group: pr-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    id-token: write

jobs:
    ci:
        name: Backend PR checks
        uses: ./.github/workflows/ci-reusable.yml
        with:
            run_checkstyle: true
            run_tests: true
            build_image: false
            run_data_tests: true
            run_checkov: true            
            run_trivy: true
            run_sbom: true
        secrets: inherit
